/* apiCEP's bank vocabulary (validation spec D12). Kept in step with
   docs/integrations/apicep.md — this file was generated from that list,
   because a name that drifts fails silently rather than loudly.

   Measured 2026-08-19: apiCEP never rejects a bank name. It aliases a
   near-miss ("Nu" resolved to NUBANK and validated) and answers `invalid`,
   with no cepDetails, when the name is a different real bank — the same
   faceless response a transfer that never happened returns. No provider
   status code will ever tell a caller its picker is wrong, so this list is
   the only thing standing between a real payment and a silent false
   rejection.

   Served at GET /banks so an integrator's picker is generated, not
   transcribed a third time. */

export const BANKS = [
  "ACTINVER",
  "AFIRME",
  "albo",
  "ARCUS FI",
  "ASP INTEGRA OPC",
  "AZTECA",
  "BaBien",
  "BAJIO",
  "BANAMEX",
  "BANCO COVALTO",
  "BANCOMEXT",
  "BANCOPPEL",
  "BANCO S3",
  "BANCREA",
  "BANJERCITO",
  "BANKAOOL",
  "BANK OF AMERICA",
  "BANK OF CHINA",
  "BANOBRAS",
  "BANORTE",
  "BANREGIO",
  "BANSI",
  "BANXICO",
  "BARCLAYS",
  "BBASE",
  "BBVA MEXICO",
  "BMONEX",
  "CAJA POP MEXICA",
  "CAJA TELEFONIST",
  "CASHI CUENTA",
  "CB INTERCAM",
  "CI BOLSA",
  "CITI MEXICO",
  "CLS",
  "CoDi Valida",
  "COMPARTAMOS",
  "CONSUBANCO",
  "COOPDESARROLLO",
  "CREDICAPITAL",
  "CREDICLUB",
  "CRISTOBAL COLON",
  "Cuenca",
  "Dep y Pag Dig",
  "DONDE",
  "FINAMEX",
  "FINCOMUN",
  "FINCO PAY",
  "FONDEADORA",
  "FONDO (FIRA)",
  "GBM",
  "HEY BANCO",
  "HIPOTECARIA FED",
  "HSBC",
  "ICBC",
  "INBURSA",
  "INDEVAL",
  "INMOBILIARIO",
  "INTERCAM BANCO",
  "INVEX",
  "JP MORGAN",
  "KAPITAL",
  "KLAR",
  "KUSPIT",
  "LIBERTAD",
  "MASARI",
  "Mercado Pago W",
  "MexPago",
  "MIFEL",
  "MIZUHO BANK",
  "MONEXCB",
  "MUFG",
  "MULTIVA BANCO",
  "NAFIN",
  "NUBANK",
  "NVIO",
  "PAGATODO",
  "Peibo",
  "PROFUTURO",
  "REVOLUT",
  "SABADELL",
  "SANTANDER",
  "SCOTIABANK",
  "SHINHAN",
  "SPIN BY OXXO",
  "STP",
  "TESORED",
  "TRANSFER",
  "UALA",
  "UBER PRO CARD",
  "UNAGRA",
  "VALMEX",
  "VALUE",
  "VECTOR",
  "VE POR MAS",
  "VOLKSWAGEN",
  "TRF",
  "CLIP",
] as const;

export type Bank = (typeof BANKS)[number];
