#!/usr/bin/env node
/* One vocabulary, three places that must agree: apiCEP's contract file,
   Consta's request schema and Devolada's payer form. This generates the two
   TypeScript constants from the documented list so a name cannot drift
   between them — and drift here fails silently, which is the whole problem
   (Consta validation spec D12, docs/legacy/integrations/apicep.md).

     node scripts/gen-banks.mjs           rewrite both constants
     node scripts/gen-banks.mjs --check   fail if either is out of date (CI)
*/

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const doc = readFileSync(join(root, "docs/legacy/integrations/apicep.md"), "utf8");

/* The vocabulary paragraph: every backticked span between the list's first
   entry and the prose that follows it. */
const start = doc.indexOf("`ACTINVER`");
const end = doc.indexOf("The names are not the ones");
if (start < 0 || end < 0 || end < start) {
  console.error("gen-banks: could not find the bank vocabulary in docs/legacy/integrations/apicep.md");
  process.exit(1);
}
const banks = [...doc.slice(start, end).matchAll(/`([^`]+)`/g)].map((m) => m[1]);

if (banks.length < 50 || new Set(banks).size !== banks.length) {
  console.error(`gen-banks: refusing a suspicious list (${banks.length} entries, ${new Set(banks).size} unique)`);
  process.exit(1);
}

const preamble = `/* GENERATED by scripts/gen-banks.mjs from docs/legacy/integrations/apicep.md.
   Do not edit by hand — edit the doc and re-run the script.

   Measured 2026-08-19: apiCEP never rejects a bank name. It aliases a
   near-miss ("Nu" resolved to NUBANK and validated) and answers \`invalid\`,
   with no cepDetails, when the name is a different real bank — the same
   faceless response a transfer that never happened returns. No provider
   status code will ever say the picker was wrong, so this list is the only
   thing standing between a real payment and a silent false rejection.`;

const targets = [
  {
    path: "apps/consta/src/provider/banks.ts",
    header: `${preamble}

   Consta validation spec D12. Served at GET /banks so an integrator's picker
   is generated, not transcribed a third time. */`,
  },
  {
    path: "apps/api/src/direct-payments/banks.ts",
    header: `${preamble}

   direct-payment spec D16. Devolada holds its own copy rather than calling
   Consta for a static list: the payer's form needs it at page load, and a
   network hop to render a dropdown would be a new way for the page to fail.
   BUG-007 is what this closes. */`,
  },
];

let drifted = false;
for (const { path, header } of targets) {
  const body = banks.map((b) => `  ${JSON.stringify(b)},`).join("\n");
  const next = `${header}\n\nexport const BANKS = [\n${body}\n] as const;\n\nexport type Bank = (typeof BANKS)[number];\n`;
  const full = join(root, path);
  const current = (() => {
    try {
      return readFileSync(full, "utf8");
    } catch {
      return null;
    }
  })();
  if (current === next) continue;
  if (process.argv.includes("--check")) {
    console.error(`✘ ${path} is out of date — run: node scripts/gen-banks.mjs`);
    drifted = true;
    continue;
  }
  writeFileSync(full, next);
  console.log(`✔ ${path} (${banks.length} banks)`);
}

if (drifted) process.exit(1);
if (process.argv.includes("--check")) console.log(`✔ gen-banks: ${banks.length} banks, both constants in step`);
