#!/usr/bin/env node
/* One vocabulary, two places that must agree: apiCEP's contract file and
   the product's constant — which the payer's form, the engine's request
   guard and its reader all import. This generates the TypeScript constant
   from the documented list so a name cannot drift from the contract — and
   drift here fails silently, which is the whole problem (Consta validation
   spec D12). The vocabulary lives in scripts/banks.data.md, lifted from the
   apiCEP contract file now archived in
   leolicona/devoladapago-legacy-documentation.

   Until consta-api-merge D14 there were two constants, one per Worker;
   the engine is a module of the API now and imports the API's own.

     node scripts/gen-banks.mjs           rewrite the constant
     node scripts/gen-banks.mjs --check   fail if it is out of date (CI)
*/

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const doc = readFileSync(join(root, "scripts/banks.data.md"), "utf8");

/* The vocabulary paragraph: every backticked span between the list's first
   entry and the prose that follows it. */
const start = doc.indexOf("`ACTINVER`");
const end = doc.indexOf("The names are not the ones");
if (start < 0 || end < 0 || end < start) {
  console.error("gen-banks: could not find the bank vocabulary in scripts/banks.data.md");
  process.exit(1);
}
const banks = [...doc.slice(start, end).matchAll(/`([^`]+)`/g)].map((m) => m[1]);

if (banks.length < 50 || new Set(banks).size !== banks.length) {
  console.error(`gen-banks: refusing a suspicious list (${banks.length} entries, ${new Set(banks).size} unique)`);
  process.exit(1);
}

const preamble = `/* GENERATED by scripts/gen-banks.mjs from scripts/banks.data.md.
   Do not edit by hand — edit scripts/banks.data.md and re-run the script.

   Measured 2026-08-19: apiCEP never rejects a bank name. It aliases a
   near-miss ("Nu" resolved to NUBANK and validated) and answers \`invalid\`,
   with no cepDetails, when the name is a different real bank — the same
   faceless response a transfer that never happened returns. No provider
   status code will ever say the picker was wrong, so this list is the only
   thing standing between a real payment and a silent false rejection.`;

const targets = [
  {
    path: "apps/api/src/direct-payments/banks.ts",
    header: `${preamble}

   direct-payment spec D16, Consta validation spec D12. One constant for the
   payer's form, the engine's request guard and its reader (consta-api-merge
   D14): the form needs it at page load, and the guard is what turns a
   silent false rejection into a fixable refusal. BUG-007 is what this
   closes. */`,
  },
];

let drifted = false;
for (const { path, header } of targets) {
  const body = banks.map((b) => `  ${JSON.stringify(b)},`).join("\n");
  const next = `${header}\n\nexport const BANKS = [\n${body}\n] as const;\n\nexport type Bank = (typeof BANKS)[number];\n`;
  const full = join(root, path);
  const current = (() => {
    try {
      return readFileSync(full, "utf8");
    } catch {
      return null;
    }
  })();
  if (current === next) continue;
  if (process.argv.includes("--check")) {
    console.error(`✘ ${path} is out of date — run: node scripts/gen-banks.mjs`);
    drifted = true;
    continue;
  }
  writeFileSync(full, next);
  console.log(`✔ ${path} (${banks.length} banks)`);
}

if (drifted) process.exit(1);
if (process.argv.includes("--check")) console.log(`✔ gen-banks: ${banks.length} banks, the constant in step`);
